version: '3'
services:
  postgres:
    container_name: "postgres"
    image: "postgres:13-alpine"
    ports:
      - "43167:5432" # PostGres
    environment:
      - POSTGRES_USER=hadesusr
      - POSTGRES_PASSWORD=hadespwd
      - PGDATA=/pg-data
      - POSTGRES_DB=hades    # This is the name of the database to be created
      - POSTGRES_LOG_STATEMENT=all
      - POSTGRES_LOG_DESTINATION=stderr
    volumes:
      - $HOME/hrt/vol/postgres/hades:/pg-data
      - $HOME/hrt/boot/server/database/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
    user: "502:20"
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    # ! To avoid "chown: /pg-data: Permission denied", run as UID:GID of the host user `ls -nd $HOME/hrt/vol/postgres/hades`
    # * Use spring.jpa.hibernate.ddl-auto=create-drop to recreate the database schema
