version: '3.8'
services:
  sftp-server:
    container_name: "sftp-server"
    hostname: sshd.ctr
    build:
      context: ${HOME}/hrt/boot/server/sftp
      # build arguments are accessible only during build time whereas environment variables are accessible during run time.
      args:
        SSH_MASTER_USER: gaia
        SSH_MASTER_PASS: gaiapwd
    ports:
      - "4319:22" # Sftp
    volumes:
      - sftp-data:/sftp/data

  sftp-go:
    container_name: "sftp-go"
    image: "drakkan/sftpgo"
    ports:
      - "43197:8080"    # Sftp-Go
      - "43196:2022"    # SFtp
    restart: "always"
    profiles:
      - back-burner

#_Named Volume_ : for sharing data between different services' containers
#   or persisting data between runs of different containers for the same service.
# docker-compose down --volumes : to remove named volumes
volumes:
    sftp-data:
