# Customise the Powerlevel9k prompts
# https://github.com/Powerlevel9k/powerlevel9k#prompt-customization
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
 #ssh
  context
  dir_writable
  vcs
  # newline
)

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status
  command_execution_time
  background_jobs
  virtualenv
  pyenv
  aws
  dir
  history
  time
)

POWERLEVEL9K_MODE=nerdfont-complete

POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
    
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=5

POWERLEVEL9K_SHORTEN_DIR_LENGTH=5
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique



POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B0'
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B2'

POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=0
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=3
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_VISUAL_IDENTIFIER_EXPANSION=
