# UV Configuration File
# XDG-compliant Python package management

# Cache configuration
cache-dir = "$XDG_CACHE_HOME/uv"

# Package index configuration
index-url = "https://pypi.org/simple/"

# Resolution strategy - prefer latest compatible versions
resolution = "highest"

# Compile bytecode for faster startup
compile-bytecode = true

# Link mode for installations (copy, hardlink, or symlink)
link-mode = "copy"

# Enable keyring for credential storage
keyring-provider = "subprocess"
